apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-k8s-app
  namespace: dev
  annotations:
      circleci.com/project-id: 34b5068e-88b8-4062-804a-633ab5ce1622
  labels:
      circleci.com/component-name: my-k8s-app
      circleci.com/version: 1.0.0
      app: my-k8s-app
spec:
  selector:
    matchLabels:
      app: my-k8s-app
  template:
    metadata:
      labels:
        app: my-k8s-app
        circleci.com/component-name: my-k8s-app
        circleci.com/version: 1.0.0
    spec:
      containers:
      - name: my-container
        image: krislamb21/my-k8s-app:dev
        ports:
        - containerPort: 3000
